---
name: format
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
permissions:
  contents: write
  pull-requests: write
jobs:
  format:
    runs-on: ubuntu-latest
    env:
      DOCKER_CMD: "node --version && npm --version"
      SAFE_CHAIN_MINIMUM_PACKAGE_AGE_HOURS: 168 # 7日
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{steps.generate_token.outputs.token}}
          persist-credentials: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          node-version-file: package.json
          cache: npm
      - name: Update packages
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: |
          curl -fsSL https://raw.githubusercontent.com/AikidoSec/safe-chain/main/install-scripts/install-safe-chain.sh | sh -s -- --ci
          npm install
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: bash "${GITHUB_WORKSPACE}/scripts/format/format/format.sh"
      - uses: dev-hato/actions-diff-pr-management@b446497d139ed3eadc62ec1dd90dd27960ad1a0c # v2.2.4
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          branch-name-prefix: fix-format
          pr-title-prefix: formatを直してあげたよ！
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
